version: '3.8'

services:
  backend:
    build: .
    container_name: backend-app
    ports:
    
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
